apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: staging-common
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: staging-common
  namespace: argocd
spec:
  destination:
    namespace: staging-common
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-master/staging/common/src
    repoURL: https://github.com/oyas/argocd-test
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    validate: true
