apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pf
  namespace: argocd
spec:
  destination:
    namespace: pf-alpha-service-echo
  source:
    path: separate/apps/service_echo/overlays/ALPHA/
    repoURL: https://github.com/oyas/argocd-test
    targetRevision: HEAD
