apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: echo-container
        image: hashicorp/http-echo
        args: ["-listen=:8080", "-text='hello world'"]
        ports:
        - containerPort: 8080
