apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-echo
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app-template: http-echo
  template:
    metadata:
      labels:
        app-template: http-echo
    spec:
      containers:
      - name: echo-container
        image: hashicorp/http-echo
        args: ["-listen=:8080", "-text=hello world from echo service"]
        ports:
        - containerPort: 8080
