apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pf
spec:
  destination:
    namespace: pf-staging
  project: default
  source:
    path: app-master/overlays/staging/
    repoURL: https://github.com/oyas/argocd-test
    targetRevision: HEAD
