# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
# - projects/alpha.yaml
# bases:
# - overlays/kustomize-guestbook
# - overlays/pre-post-sync
# - overlays/sync-waves
resources:
- all.yaml
